---
- hosts: routers
  gather_facts: false
  connection: network_cli
  vars_files:
    - vars.yaml
    - secrets.yaml


  tasks:
  - name: Configure bgp neighbor with ASN {{ remote_as }} - {{ neighbor_ip }}
    vars:
      neighbor_ip: 169.254.0.2
      password: '{{ vars["169.254.0.2_passwd"] }}'
      route_map_in: route-map-test-in
      route_map_out: route-map-test-out
    import_role:
      name: ios-bgp
